title: Mohammad Khodaparastan
description: Mohammad Khodaparastan / Trading Diary

author: Mohammad Khodaparastan
email: mkhmac@gmail.com
timezone: +04:30

url: https://khodaparastan.com
root: /
static: /static
imageurl: /static/images
icon: /static/theme/mkh/img/logo.png

post_num: all
archive_post_num: all
feed_output: atom.xml

default_floor: fa
default_markup: mmd

disqus_shortname: mkhmac
google_analytics: UA-99040001-1

twitter: https://twitter.com/mkhmac
github: https://github.com/mkhmac
tradingview: https://www.tradingview.com/u/mkhmac/
telegram: https://t.me/mkhmac
linkenin: 
